<?php
declare(strict_types=1);

namespace Tests;

use Aoc\CustomCustoms\Grouper;
use Aoc\TobogganTrajectory\Router;
use PHPUnit\Framework\TestCase;

class CustomCustomsTest extends TestCase
{
    private array $input = [];
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->input = [
            "abc",
            "",
            "a",
            "b",
            "c",
            "",
            "ab",
            "ac",
            "",
            "a",
            "a",
            "a",
            "a",
            "",
            "b",
        ];
    }

    public function testCountGroupsInInput(): void
    {
        $grouper = new Grouper($this->input);

        $this->assertEquals(5, count($grouper->groups()));
    }

    public function testSumYesesInGroups(): void
    {
        $grouper = new Grouper($this->input);

        $this->assertEquals(11, $grouper->sum());

    }
}
