<?php

declare(strict_types=1);

namespace Tests;

use Aoc\EncodingError\Calculator;
use Aoc\EncodingError\SumCalculator;
use PHPUnit\Framework\TestCase;

class EncodingErrorTest extends TestCase
{
    private array $input = [];

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->input = [
            "35",
            "20",
            "15",
            "25",
            "47",
            "40",
            "62",
            "55",
            "65",
            "95",
            "102",
            "117",
            "150",
            "182",
            "127",
            "219",
            "299",
            "277",
            "309",
            "576",
        ];
    }

    public function testFindWhichIsNotSum(): void
    {
        $calculator = new Calculator($this->input, 25);
        $this->assertEquals(127, $calculator->firstNotSum());
    }

    public function testContiguousSetOfNumbersProducesSumWhichIsInvalidNumber(): void
    {
        $calculator = new SumCalculator($this->input, 127);
        $this->assertEquals(62, $calculator->sum());
    }
}
