<?php
declare(strict_types=1);

namespace Tests;

use Aoc\Password\Counter;
use Aoc\Password\Parser;
use Aoc\Password\PasswordValidator;
use PHPUnit\Framework\TestCase;

class PasswordTest extends TestCase
{
    private array $passwords = [];

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->passwords = [
            "1-3 a: abcde",
            "1-3 b: cdefg",
            "2-9 c: ccccccccc"
        ];
    }

    public function testParser()
    {
        $parser = new Parser();
        $result = $parser->parse("1-3 a: abcde");
        $this->assertSame([[1,3], 'a', "abcde"], $result);
    }

    public function testValidPassword()
    {
        $validator = new PasswordValidator();
        $this->assertTrue($validator->validate([1,3], 'a', "abcde"));
    }

    public function testInvalidPassword()
    {
        $validator = new PasswordValidator();
        $this->assertFalse($validator->validate([1,3], 'b', "cdefg"));
    }

    public function testCounter()
    {
        $counter = new Counter($this->passwords, new Parser(), new PasswordValidator());
        $this->assertSame(2, $counter->count());
    }


}
